web/router.ex
defmodule Gotv.Router do
  use Gotv.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Gotv do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/subscribers", SubscriberController, only: [:create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Gotv do
  #   pipe_through :api
  # end
end

lib/gotv/endpoint.ex
defmodule Gotv.Endpoint do
  use Phoenix.Endpoint, otp_app: :gotv

  socket "/socket", Gotv.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :gotv, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_gotv_key",
    signing_salt: "6rk63/hz"

  plug Gotv.Router
end

lib/gotv/repo.ex
defmodule Gotv.Repo do
  use Ecto.Repo, otp_app: :gotv
end

web/models/subscriber.ex
defmodule Gotv.Subscriber do
  use Gotv.Web, :model

  schema "subscribers" do
    field :first_name, :string
    field :last_name, :string
    field :email_address, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:first_name, :last_name, :email_address])
    |> validate_required([:email_address])
    |> validate_format(:email_address, ~r/@[a-z\d\-.]+\.[a-z]+\z/i)
  end
end

web/controllers/page_controller.ex
defmodule Gotv.PageController do
  use Gotv.Web, :controller

  alias Gotv.Subscriber

  def index(conn, _params) do
    changeset = Subscriber.changeset(%Subscriber{})
    render conn, "index.html", changeset: changeset
  end
end

web/controllers/subscriber_controller.ex
defmodule Gotv.SubscriberController do
  use Gotv.Web, :controller

  alias Gotv.Subscriber

  def create(conn, %{"subscriber" => subscriber_params}) do
    changeset = Subscriber.changeset(%Subscriber{}, subscriber_params)
    case Repo.insert(changeset) do
      {:ok, _subscriber} ->
        conn
        |> put_flash(:info, "You have subscribed successfully and you will receive email reminders to vote!")
        |> redirect(to: page_path(conn, :index))
      {:error, changeset} ->
        render(conn, Gotv.PageView, "index.html", changeset: changeset)
    end
  end
end

web/views/error_view.ex
defmodule Gotv.ErrorView do
  use Gotv.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Gotv.LayoutView do
  use Gotv.Web, :view
end

web/views/page_view.ex
defmodule Gotv.PageView do
  use Gotv.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Municipal Election Dates: Primary Election - September 10th  | General Election - November 5th">

    <title>Toledo Get Out the Vote | GOTV</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-100785822-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>

  <body>
    <header>
      <h1>toledoGO.TV <span>|</span> Get&nbsp;Out&nbsp;The&nbsp;Vote</h1>
      <div class='dates'>Municipal Election Dates: Primary&nbsp;Election&nbsp;-&nbsp;September&nbsp;10th <span>|</span> General&nbsp;Election&nbsp;-&nbsp;November&nbsp;5th</div>
    </header>

    <%= if get_flash(@conn, :info) do %>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <% end %>
    <%= if get_flash(@conn, :error) do %>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <% end %>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer>
      <p>Paid for by Friends of Sam Melden</p>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<section class="hero">
  <div class="hero__block">
    <h1>Your voice matters…<br>Vote!</h1>
  </div>
  <div class="hero__block">
    <p>Not registered to vote?<br><a href="https://olvr.sos.state.oh.us/" target="_blank">Register here!</a></p>
    <p>Recently moved or unsure of registration?<br><a href="https://olvr.sos.state.oh.us/" target="_blank">Update your registration here!</a></p>
  </div>
</section>

<section class="email">
  <h2>Sign up to receive voting reminders and a link to help find your polling location!</h2>
  <div class="signup">
    <%= form_for @changeset, subscriber_path(@conn, :create), fn f -> %>
      <%= if @changeset.action do %>
        <div class="alert alert-danger">
          <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
      <% end %>

      <label>
        <span>Email:</span>
        <%= text_input f, :email_address, type: "email", placeholder: "you@yours.com" %>
        <%= error_tag f, :email_address %>
      </label>
      <button type="submit">Sign up!</button>
    <% end %>
  </div>
</section>

<section class="location">
  <h2>Do you know where you vote?</h2>
  <p>To find your polling location go <a href="https://lucas.oh-vote.org/VoterView/PollingPlaceSearch.do" target="_blank">here.</a></p>
</section>